branch-defaults:
  develop:
    environment: engage-web-api-dev
    group_suffix: null
  master:
    environment: engage-web-api-dev
    group_suffix: null
global:
  application_name: engage-web-api
  branch: develop
  default_ec2_keyname: null
  default_platform: Node.js running on 64bit Amazon Linux
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-deploy-user
  repository: null
  sc: git
  workspace_type: Application
