version: '3.1'
# Use: "docker-compose up -d" to run on detatched mode
services:
  # POSTGRES DB
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: root

    postgresTest:
      container_name: postgresTest
      image: postgres
      restart: unless-stopped
      ports:
        - '5433:5432'
      environment:
        POSTGRES_PASSWORD: root

    # REDIS DB
    redis:
      container_name: redis
      image: redis
      restart: unless-stopped
      # Command: redis-server --requirepass RedisArtio2020!
      ports:
        - '6379:6379'

    localstack:
      image: localstack/localstack
      restart: unless-stopped
      ports:
        - "4566-4584:4566-4584"
        - "8081-8081:8081-8081"
      environment:
        - SERVICES=s3,ses,dynamodb
        - DATA_DIR=/tmp/localstack/data
        - PORT_WEB_UI=8081
        - DOCKER_HOST=unix:///var/run/docker.sock
      volumes:
        - '/private/tmp/localstack:/tmp/localstack'
        - '/var/run/docker.sock:/var/run/docker.sock'
